import localFont from "next/font/local";
import "./styles/style.sass";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const montrealMed = localFont({
  src: "./fonts/PPNeueMontreal-Medium.otf",
  variable: "--font-montreal-medium",
  weight: "500",
});

const montrealBook = localFont({
  src: "./fonts/PPNeueMontreal-Book.otf",
  variable: "--font-montreal-book",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montrealMed.variable} ${montrealBook.variable}`}>
        <NavBar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
